Week Two Milestone Reached
PurpleNinjaLink/Directed-Study-FA19 pull request #6
Opened 2019-09-13 17:38 UTC by PurpleNinjaLink

The player can speak to two NPCs, one of whom offers a quest. The quest is completed by speaking to the other NPC and returning to the first.

2019-09-15 22:16 UTC, dantogno commented
@PurpleNinjaLink Did you add any scripts here? Remember, if you're going to import a bunch of stuff, do that in it's own PR so I don't have to search through thousands of files to see what you actually authored.

2019-09-15 22:29 UTC, dantogno commented
Also, good news, LFS is working! 🎊

2019-09-15 22:42 UTC, PurpleNinjaLink commented
I didn't add any scripts here, no. There are a couple more changes I might like to make before the PR is finalized--I expected I would need to revise things before it was approved. Good that LFS is working, though! My only imports are in the specified commit.

2019-09-16 23:34 UTC, PurpleNinjaLink commented
I have now added one script, which is largely comprised of repurposed code from the MovePlayer script. At some point, perhaps I should make a more general animation script which can be used by both the player and the NPCs.

2019-09-17 14:16 UTC, dantogno reviewed
How were you able to accomplish this just by changing the scene file?

2019-09-17 14:17 UTC, dantogno commented
This is too many files, I can't review it. We can look at it when we meet.

2019-09-17 15:49 UTC, PurpleNinjaLink commented
I'm not sure what you mean by too many files... when I selected only the most recent 3 commits, there were 38 changed files, most of which were animation and meta files. If I've done something wrong in that regard, I'm not sure what it was. And for stopping the player from moving while talking, there was a quick solution in the triggers and interactions tutorial to simply disable the movement script when a conversation started and enable it when the conversation ends. I thought that would be the cleanest option.

2019-09-17 19:13 UTC, dantogno requested changes

2019-09-17 19:13 UTC, dantogno commented on Assets/Scripts/AnimateNPC.cs
> +    /// Sets the NPC's animation direction to face the player initiating the conversation
Explain in the summary where / how this gets called

2019-09-17 19:13 UTC, dantogno commented on Assets/Scripts/AnimateNPC.cs
> +    /// Creates a normalized directional vector from the distance between the NPC and player
just explain this a bit more clearly if possible

2019-09-17 19:13 UTC, dantogno commented on Assets/Scripts/AnimateNPC.cs
> +    /// Creates a normalized directional vector from the distance between the NPC and player
consider renaming. My understanding is that this returns a 1 unit vector 2 pointed from the npc to the player. So figure out how to say that / name it.

2019-09-19 15:30 UTC, merged